### ISSUE TITLE
Buttons not recognized

### ISSUE THREAD

**Issue by Mixinu** [HisashiKato/USB_Host_Shield_Library_2.0_BTXBOX#1]
Hello, 

Thanks so much for taking the time to edit this library to add Bluetooth support for Xbox One controller. IT WORKS!

All analog inputs and the Hat switch (D-pad) are working.

But there is a problem with the normal buttons: only 6 of them are recognized when I run the test sketch on the serial monitor. There is no response when pressing X, RB, LSB, RSB and Xbox button.

I'm using an Xbox One S Controller (model 1708) with a compatible Bluetooth 4.0 dongle, which I tested and work fine. So it looks a library related issue.

Any idea hot to fix it?

**Comment by HisashiKato** [comment]
Thank you for using this library.

For my controller, this xboxonebtparser.cpp handles button input correctly.
The firmware of the controller I am using is the latest 4.8.1923.0.
Different firmware may result in different data being sent.
Is your controller firmware up to date?
Please check and if not, try updating the firmware.

**Comment by HisashiKato** [comment]
I accidentally closed it.

**Comment by Mixinu** [comment]
You were right. My controller firmware 3.1.1221.0 was the problem. After updating to the last 4.8.1923.0 it now works perfect!  Thanks!

All buttons are now correctly detected, except the Sync button. Do you think it is even possible to detect the Sync button? 

I had a sketch that recognizes all buttons including the Sync button (with the controller directly connected to the USB host shield through a USB cable) using something like Xbox.getButtonPress(SYNC) from  XBOXONE.cpp in the original library, but I'm not sure if that's also possible through Bluetooth.

**Comment by HisashiKato** [comment]
The data that the controller sends to the host via Bluetooth wireless connection is different from the data that the controller sends to the host via USB wired connection.

There was no Sync button's information in the data that the controller sends to the host via Bluetooth wireless connection. (I couldn't find it)

So it's impossible for me.

**Comment by Mixinu** [comment]
I see, it's a pity there is no way to access the Sync button via Bluetooth but I was already expecting that.

Anyway, I'm already very happy. I wanted to control Arduino wireless from a Xbox One controller for a long time and could never figure it out, so this really made my day. Very grateful! It's going to be a lot of fun to play with it.

Have a nice day and keep the good work!
