### ISSUE TITLE
Pair with XBOX ONE controller

### ISSUE THREAD

**Issue by JorgeLiberato** [HisashiKato/USB_Host_Shield_Library_2.0_BTXBOX#2]
Hello!

I am currently trying to connect an Arduino Mega 2560 to a xbox one controller via bluetooth. I read all of the forum that you mentionned but i still can't make it work. I can't even pair. Could you do some kind of tutorial? I know it is ask for too much, but i can't really understand how to proceed.
I appreciate. 
Thank you very much!

**Comment by HisashiKato** [comment]
@JorgeLiberato

First
Will your USB mouse or USB keyboard work when you connect your USB mouse or USB keyboard to your Arduino board and USB Host Shield 2.0 and run the USBHIDBootMouse or USBHIDBootKbd of the original USB host library 2.0 ?

Next
Will your Bluetooth mouse or Bluetooth keyboard work when you connect your Bluetooth USB adapter to your Arduino board and USB Host Shield 2.0 and run the BTHID of the original USB host library 2.0?

Tell me  please.

**Comment by JorgeLiberato** [comment]
Actually, in the original library my xbox one controller only works with the usb cable.

**Comment by HisashiKato** [comment]
Will your Bluetooth mouse or Bluetooth keyboard work when you connect your Bluetooth USB adapter to your Arduino board and USB Host Shield 2.0 and run the BTHID of the original USB host library 2.0?

I want to know if the hardware is working properly.

**Comment by JorgeLiberato** [comment]
Absolutely! I have tested and it is everything working

**Comment by HisashiKato** [comment]
OK.
From here, it is about "BTXBOX Library".

Please enable serial debugging.
"settings.h"Line 35 delete "//"

#define ENABLE_UHS_DEBUGGING 1

And please tell me the message that is displayed.


I can hardly speak English.
I rely on Google Translate to write these.
I'm sorry.

**Comment by JorgeLiberato** [comment]
Hello HisashiKato! Sorry for taking so long to answer you. I deleted the "//" in the line 35 of settings.h and this happen:

Start
XBOX Bluetooth Library Started

Bluetooth Dongle Initialized
HCI Reset complete
Write class of device
Simple pairing was enabled
Set Event Mask
HCI_CHECK_DEVICE_SERVICE
pairWithHIDDevice = 01
Please enable discovery of your device.
Couldn't find HID device
hci_state = HCI_SCANNING_STATE_INQUIRY_COMPLETE
HCI_SCANNING_STATE:
connectToHIDDevice:00
pairWithHIDDevice:00
Wait For Incoming Connection Request

**Comment by JorgeLiberato** [comment]
I don't know if i missed anything. But i turn on the arduino with the usb host shield and the bluetooth 4.0 dongle. Then, i press the synchronization button in the controller.

**Comment by HisashiKato** [comment]
Perhaps your controller hasn't signaled a pairing request.
The controller has not switched to pairing mode.
Please read the following page.

[https://support.xbox.com/en-US/help/hardware-network/accessories/connect-and-troubleshoot-xbox-one-bluetooth-issues](https://support.xbox.com/en-US/help/hardware-network/accessories/connect-and-troubleshoot-xbox-one-bluetooth-issues)

1.Make sure you have updated your controller.
2. Turn on your controller by pressing the Xbox button.
3.Press the controller’s Pair button for 3 seconds and release. (Xbox button flashes faster.The controller goes into pairing mode.)

**Comment by JorgeLiberato** [comment]
I already updated my controller and i did the steps that you talked, but nothing happens. The same output came.

**Comment by HisashiKato** [comment]
I can't do anything more.
I'm sorry.

**Comment by HisashiKato** [comment]
I write specifically what is happening.

After the USB Host Shield initializes the Bluetooth USB adapter, the host shield sends a command to the Bluetooth adapter to find the device.
But the Bluetooth adapter has not sent a reply to the Host Shield that it has found the device.

**Comment by HisashiKato** [comment]
The following is an example of a debug message when it is working properly.

```Start
XBOX Bluetooth Library Started

Bluetooth Dongle Initialized
No response to HCI Reset
HCI Reset complete
Write class of device
Simple pairing was enabled
Set Event Mask
HCI_CHECK_DEVICE_SERVICE
pairWithHIDDevice = 01
Please enable discovery of your device.
Gamepad found
BD_ADDR: 98:7A:14:30:4D:5C
HID device found
Remote Name: Xbox Wireless Controller
Connecting to HID device
EV_CONNECTION_COMPLETE:Connection established
Connected to HID device
EV_LINK_KEY_REQUEST 
pairWithHIDDevice = 01
hci_link_key_request_negative_reply
Start Simple Pairing
Received IO Capability Request: 
User confirmation Request: 
Link Key Notification
EV_AUTHENTICATION_COMPLETE
Pairing successful with HID device
pairWithHIDDevice:01
connectToHIDDevice:01
Send HID Control Connection Request
EV_Encryption Changed
EV_Encryption Changed
EV_Encryption Changed
Send HID Control Config Request
Set protocol mode: 01
Send HID Interrupt Connection Request
Send HID Interrupt Config Request
HID Channels Established   X: 8ABF  Y: 82B7   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000

HCI_DONE_STATE: >>> HCI_DISCONNECT_STATE:   X: 8ABF  Y: 825D   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8B4B  Y: 825D   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8B4B  Y: 81E3   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8BDF  Y: 81E3   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8BDF  Y: 816A   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8C66  Y: 816A   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8CC5  Y: 80FB   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8CC5  Y: 818F   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8D27  Y: 818F   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8D27  Y: 821C   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8D27  Y: 8275   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8CA9  Y: 82DE   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8C32  Y: 82DE   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8C32  Y: 835A   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8BBC  Y: 835A   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8BBC  Y: 83B6   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8B5B  Y: 83B6   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8B5B  Y: 841A   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8B5B  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
Dn: 1
Up: 1
Dn: 2
Up: 2
Dn: 3
Up: 3
Dn: 4
Up: 4
Hat Switch: 07
Hat Switch: 05
Hat Switch: 04
Hat Switch: 03
Hat Switch: 02
Hat Switch: 01
Hat Switch: 07
Hat Switch: 06
Hat Switch: 05
Hat Switch: 00
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 000D
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0021
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0032
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 00A2
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 010C
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 01B7
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 025D
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 026C
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0275
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 026F
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 019E
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0098
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 00B1   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0191   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0231   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0241   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 024E   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0257   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0259   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0251   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 01DB   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0170   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 015E   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 008C   RT: 0000
   X: 8AF6  Y: 8477   Z1: 7AB7  Z2: 884A   LT: 0000   RT: 0000
```

**Comment by JorgeLiberato** [comment]
I will try to change controller or the USB host shield. Anyway, thanks for your effort =]

**Comment by HisashiKato** [comment]
It could also be due to the Bluetooth USB adapter.
Try connecting your Bluetooth USB adapter to your PC and see if your PC and your XBOX ONE S controller connect via Bluetooth.
